/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Frametujuan.java
 *
 * Created on Mar 4, 2021, 3:39:59 PM
 */

/**
 *
 * @author fadil
 */
public class Frametujuan extends javax.swing.JInternalFrame {

    /** Creates new form Frametujuan */
    public Frametujuan() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pgl = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        pgl.setText("Panggil");
        pgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pglActionPerformed(evt);
            }
        });

        jLabel1.setText("Memanggil Frame Yang Lain");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(pgl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel1)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(pgl)
                .addGap(93, 93, 93))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pglActionPerformed
        // TODO add your handling code here:
        new Frametujuan().setVisible(true);
    }//GEN-LAST:event_pglActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton pgl;
    // End of variables declaration//GEN-END:variables

}
